CREATE TABLE IF NOT EXISTS Users (
  id VARCHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Bookings (
  id VARCHAR(36) PRIMARY KEY,
  room_id VARCHAR(255) NOT NULL,
  guest_name VARCHAR(255) NOT NULL,
  check_in_date DATE NOT NULL,
  check_out_date DATE NOT NULL,
  user_id VARCHAR(36),
  FOREIGN KEY (user_id) REFERENCES Users(id)
);